export const schemaCuota = {
  labels: {
    singular: 'Plan de Pago',
    plural: 'Plan de Pagos',
  },
  requiredProperties: ['cuota_separacion', 'fecha_cuota', 'numero_cuota', 'valor'],
  searchableProperties: ['cuota_separacion', 'fecha_cuota', 'numero_cuota', 'valor', 'fixed_value'],
  secondaryDisplayProperties: ['fecha_cuota', 'valor'],
  associatedObjects: ['CONTACT', 'DEAL'],
  name: 'planpago',
  primaryDisplayProperty: 'name',
  properties: [
    {
      name: 'cuota_separacion',
      label: 'Cuota Separación',
      isPrimaryDisplayLabel: true,
      description: 'Es una cuota de separacion o es un pago mensual de la cuota inicial',
      displayOrder: 5,
      type: 'bool',
      fieldType: 'booleancheckbox',
      options: [
        {
          label: 'Si',
          value: 'true',
          displayOrder: 0,
        },
        {
          label: 'No',
          value: 'false',
          displayOrder: 1,
        },
      ],
    },
    {
      name: 'fecha_cuota',
      label: 'Fecha Cuota',
      description: 'Fecha estimada para el pago de la cuota',
      displayOrder: 4,
      type: 'date',
      fieldType: 'date',
    },
    {
      name: 'fixed_value',
      label: 'Valor Fijado',
      description:
        'Es un cuota modificada por el cliente ya sea por un valor mayor o menor de acuerdo a su capacidad de pago',
      options: [
        {
          label: 'Si',
          value: 'true',
          displayOrder: 0,
        },
        {
          label: 'No',
          value: 'false',
          displayOrder: 1,
        },
      ],
      type: 'bool',
      fieldType: 'booleancheckbox',
      displayOrder: 6,
    },
    {
      name: 'numero_cuota',
      label: 'Numero de Cuota',
      description: 'Numero de la cuota',
      displayOrder: 3,
      type: 'number',
      fieldType: 'number',
    },
    {
      name: 'name',
      label: 'Nombre ID',
      description: 'Identificador de la cuota',
      displayOrder: 1,
      type: 'string',
      fieldType: 'text',
    },
    {
      name: 'valor',
      label: 'Valor',
      description: 'Valor o precio de la cuota',
      displayOrder: 2,
      type: 'number',
      fieldType: 'number',
    },
    {
      name: 'observaciones',
      label: 'Observaciones',
      description: 'Observación de pago de la cuota',
      displayOrder: 7,
      type: 'string',
      fieldType: 'textarea',
    },
    {
      name: 'link_pay',
      label: 'Enlace de Pago',
      description: 'URL del enlace de pago de la cuota',
      displayOrder: 8,
      type: 'string',
      fieldType: 'text',
    },
    {
      name: 'status',
      label: 'Estado',
      description: 'Estado de Pago',
      type: 'enumeration',
      fieldType: 'select',
      displayOrder: 9,
      options: [
        {
          description: null,
          label: '',
          displayOrder: 1,
          hidden: false,
          doubleData: null,
          readOnly: false,
          value: '',
        },
        {
          description: "La cuota esta pagada",
          label: 'Pago',
          displayOrder: 1,
          hidden: false,
          doubleData: null,
          readOnly: false,
          value: 'Pago',
        },
        {
          description: "La cuota es pendiente de pago",
          label: 'Sin Pagar',
          displayOrder: 1,
          hidden: false,
          doubleData: null,
          readOnly: false,
          value: 'Sin Pagar',
        },
      ],
    }
  ],
};
