export const dataTipo = {
  name: 'type',
  label: 'Categoria del Producto',
  description: 'Permite identificar el tipo de producto',
  groupName: 'cotizador_inmobiliario',
  type: 'enumeration',
  fieldType: 'select',
  displayOrder: 8,
  options: [
    {
      description: null,
      label: '',
      displayOrder: 1,
      hidden: false,
      doubleData: null,
      readOnly: false,
      value: '',
    },
    {
      description: null,
      label: 'Apartamento',
      displayOrder: 2,
      hidden: false,
      doubleData: null,
      readOnly: false,
      value: 'apto',
    },
    {
      description: null,
      label: 'Casa',
      displayOrder: 3,
      hidden: false,
      doubleData: null,
      readOnly: false,
      value: 'casa',
    },
    {
      description: null,
      label: 'Acabado',
      displayOrder: 3,
      hidden: false,
      doubleData: null,
      readOnly: false,
      value: 'acabado',
    },
    {
      description: null,
      label: 'Adicional',
      displayOrder: 4,
      hidden: false,
      doubleData: null,
      readOnly: false,
      value: 'adicional',
    },
  ],
};
